version: '3'
services:
  web:
    image: docker.genya0407.net/akita-feeder_web:${TAG}
    command: /go/bin/akita-feeder --port=3000
    ports:
      - "127.0.0.1:${PORT:?err}:3000"
    restart: always

